version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: faztpassword
      POSTGRES_DB: nestdb
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: